### ISSUE TITLE
OANDA v20 repetitive disconnection 

### ISSUE THREAD

**Issue by robertsim** [ftomassetti/backtrader-oandav20#54] opened 2020-07-09 08:00 UTC
Hi Federico,

Thank you for your work, really useful API. 

I have updated to this latest version this week and I seem to have a repetitive disconnection with OANDA Live and Demo.
This could be due to OANDA environments but I haven't seen any issue reported on their side so, I am posting here to check if others have the same issue too.

--------------------------------------------------
---             DATA NOTIF: LIVE
      STORE NOTIF: v20 REST request to https://stream-fxpractice.oanda.com:443/v3/accounts/101-006-13XX881-005/transactions/stream has timed out (read)

      STORE NOTIF: Trying to reconnect streaming events (1 of -1)

--------------------------------------------------
---             DATA NOTIF: DELAYED
      STORE NOTIF: v20 REST request to https://stream-fxpractice.oanda.com:443/v3/accounts/101-006-13XX881-005/transactions/stream has timed out (stream)

      STORE NOTIF: Trying to reconnect streaming events (1 of -1)

--------------------------------------------------
---             DATA NOTIF: CONNBROKEN

      STORE NOTIF: v20 REST request to https://stream-fxpractice.oanda.com:443/v3/accounts/101-006-13XX881-005/transactions/stream has timed out (read)

      STORE NOTIF: Trying to reconnect streaming events (2 of -1)
      STORE NOTIF: v20 REST request to https://stream-fxpractice.oanda.com:443/v3/accounts/101-006-13XX881-005/transactions/stream has timed out (stream)

Thanks
Rob

**Comment by data-octo** [comment] 2020-07-30 00:42
I am also having the same issue.

**Comment by robertsim** [comment] 2020-07-31 10:47
Update

OANDA support cannot reproduce this issue yet, still pending

**Comment by happydasch** [comment] 2020-07-31 10:54
Please check out the timeout and reconnections params.


https://github.com/ftomassetti/backtrader-oandav20/blob/master/btoandav20/stores/oandav20store.py

```

      - ``account_poll_freq`` (default: ``5.0``): refresh frequency for
        account value/cash refresh
     - ``stream_timeout`` (default: ``2``): timeout for stream requests
     - ``poll_timeout`` (default: ``2``): timeout for poll requests
     - ``reconnections`` (default: ``-1``): try to reconnect forever
         connection errors
     - ``reconntimeout`` (default: ``5.0``): how long to wait to reconnect
         stream (feeds have own reconnection settings)
```

**Comment by happydasch** [comment] 2020-07-31 11:03
since this is not a bug but intended behavior, i'll close this issue. If you encounter any bugs, open new issue.

**Closed by happydasch** 2020-07-31 11:03 UTC

**Comment by happydasch** [comment] 2020-09-04 14:24
feel free to post your opinions on how to change the behaviour in #57

**Comment by happydasch** [comment] 2020-09-04 21:04
@Mexflubber found the issue. It was a timezone issue in his case. See #57 for a possible solution for now.
